#!/bin/bash

python_file=$(basename $1)

SUBMIT=qsub.tmp

PWD=`pwd`
JOB_NAME=$(basename $PWD)

PARTITION=kemi1
TIME=3036:00:00
NCPUS=2 #THIS IS GIVEN IN THE SCRIPT OTHERWISE CHANGE THE SCRIPT
MEM=30GB

cat > $SUBMIT <<!EOF
#!/bin/sh
#SBATCH --job-name=$JOB_NAME
#SBATCH --nodes=1
#SBATCH --cpus-per-task=$NCPUS
#SBATCH --mem=$MEM
#SBATCH --ntasks=1
#SBATCH --error=$PWD/$JOB_NAME\_%j.err
#SBATCH --output=$PWD/$JOB_NAME\_%j.out
#SBATCH --time=$TIME
#SBATCH --partition=$PARTITION
#SBATCH --no-requeue

# Create scratch folder
#mkdir /scratch/\$SLURM_JOB_ID
cd /scratch/\$SLURM_JOB_ID

/groups/kemi/ree/anaconda3/envs/regioml/bin/python $PWD/$python_file

tar -cvzf out.tar.gz *
cp out.tar.gz $PWD/.

#rm -rf /scratch/\$SLURM_JOB_ID

!EOF

sbatch $SUBMIT


